<a href="https://colab.research.google.com/github/Sim2K/yt-comment-scraper/blob/development/YouTube_Comments_Advanced.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
dev = "AIzaSyC7pWad1ZSKauJQi7VyNAbDz66jsj6Ryb8"
vidid = "JMYQmGfTltY"

## Pull All Comments

In [9]:
import googleapiclient.discovery
import pandas as pd

api_service_name = "youtube"
api_version = "v3"
DEVELOPER_KEY = dev

youtube = googleapiclient.discovery.build(
    api_service_name, api_version, developerKey=DEVELOPER_KEY)

request = youtube.commentThreads().list(
    part="snippet,replies",
    videoId=vidid,
    maxResults=100
)

comments = []

# Execute the request.
response = request.execute()

# Get the comments from the response.
for item in response['items']:
    comment = item['snippet']['topLevelComment']['snippet']
    public = item['snippet']['isPublic']
    comments.append([
        comment['authorDisplayName'],
        comment['publishedAt'],
        comment['likeCount'],
        comment['textOriginal'],
        public
    ])

while (1 == 1):
  try:
   nextPageToken = response['nextPageToken']
  except KeyError:
   break
  nextPageToken = response['nextPageToken']
  # Create a new request object with the next page token.
  nextRequest = youtube.commentThreads().list(part="snippet", videoId=vidid, maxResults=100, pageToken=nextPageToken)
  # Execute the next request.
  response = nextRequest.execute()
  # Get the comments from the next response.
  for item in response['items']:
    comment = item['snippet']['topLevelComment']['snippet']
    public = item['snippet']['isPublic']
    comments.append([
        comment['authorDisplayName'],
        comment['publishedAt'],
        comment['likeCount'],
        comment['textOriginal'],
        public
    ])

df = pd.DataFrame(comments, columns=['author', 'updated_at', 'like_count', 'text','public'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4921 entries, 0 to 4920
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   author      4921 non-null   object
 1   updated_at  4921 non-null   object
 2   like_count  4921 non-null   int64
 3   text        4921 non-null   object
 4   public      4921 non-null   bool
dtypes: bool(1), int64(1), object(3)
memory usage: 158.7+ KB

In [10]:
response['items'][0]

{'kind': 'youtube#commentThread',
 'etag': 'vo5mafOEGTApitN_S799tHZ5QwU',
 'id': 'UgxiXHlol6MdETmuYYx4AaABAg',
 'snippet': {'channelId': 'UCGq-a57w-aPwyi3pW7XLiHw',
  'videoId': 'JMYQmGfTltY',
  'topLevelComment': {'kind': 'youtube#comment',
   'etag': 'TZwyXRPbnS_6JQZjbDIrwcuKwN8',
   'id': 'UgxiXHlol6MdETmuYYx4AaABAg',
   'snippet': {'channelId': 'UCGq-a57w-aPwyi3pW7XLiHw',
    'videoId': 'JMYQmGfTltY',
    'textDisplay': 'I look forward to more  AI. The more jobs it takes the more time people will have to consider the more important things in life.',
    'textOriginal': 'I look forward to more  AI. The more jobs it takes the more time people will have to consider the more important things in life.',
    'authorDisplayName': '@cerellitv2978',
    'authorProfileImageUrl': 'https://yt3.ggpht.com/b0dHGcfyPRNp50YdlC0TM7XOcLxfzb06kE7_yEdpQy8WMtN2gEOzmeN9j23g0byxHAefB9u-=s48-c-k-c0x00ffffff-no-rj',
    'authorChannelUrl': 'http://www.youtube.com/@cerellitv2978',
    'authorChannelId': {'value': 'UC7RIhNox-mTtle82mlOPvRA'},
    'canRate': True,
    'viewerRating': 'none',
    'likeCount': 4,
    'publishedAt': '2025-05-12T07:06:39Z',
    'updatedAt': '2025-05-12T07:06:39Z'}},
  'canReply': True,
  'totalReplyCount': 5,
  'isPublic': True}}

In [11]:
df.head(10)

,author,updated_at,like_count,text,public
0,@TheDiaryOfACEO,2025-05-12T07:01:17Z,960,question? do you like these types of convos? I...,True
1,@RealJamieBarclay,2025-05-14T13:54:54Z,0,"Just a reminder that the last AI ""Expert"" Stev...",True
2,@getdmw,2025-05-14T13:54:37Z,0,the one thing that everyone here has missed - ...,True
3,@bobloblaw3585,2025-05-14T13:54:11Z,0,Please sueprcut everything Bret said here and ...,True
4,@dungalunga2116,2025-05-14T13:53:24Z,0,the best bit was the '100 ceo' ad (blatant ai ...,True
5,@corsainstruments3569,2025-05-14T13:52:42Z,1,Was this podcast AI generated?,True
6,@Christian_Prepper,2025-05-14T13:52:16Z,1,12:02 *Bret Weinstein apparently has never wat...,True
7,@ekohdubois7950,2025-05-14T13:51:54Z,0,In the dozen debates on the subject of AI that...,True
8,@jasonrojas26,2025-05-14T13:42:42Z,0,"""Maybe they should start saving"". The arroganc...",True
9,@AaAa-je5eo,2025-05-14T13:42:18Z,0,2 and a half hours FLEW by. Incredible podcast...,True

# Pull All comments with REPLIES!

In [22]:
MAX_RESULTS = 100

def fetch_all_threads(video_id):
    threads = []
    next_page_token = None

    while True:
        resp = youtube.commentThreads().list(
            part="snippet",   # we'll fetch replies separately
            videoId=video_id,
            maxResults=MAX_RESULTS,
            pageToken=next_page_token or ""
        ).execute()

        for item in resp['items']:
            top = item['snippet']['topLevelComment']['snippet']
            threads.append({
                'thread_id': item['id'],
                'comment_id': item['snippet']['topLevelComment']['id'],
                'author': top['authorDisplayName'],
                'published_at': top['publishedAt'],
                'like_count': top['likeCount'],
                'text': top['textOriginal'],
                'is_reply': False,
                'parent_id': None
            })

        next_page_token = resp.get('nextPageToken')
        if not next_page_token:
            break

    return threads

def fetch_all_replies(parent_id):
    replies = []
    next_page_token = None

    while True:
        resp = youtube.comments().list(
            part="snippet",
            parentId=parent_id,
            maxResults=MAX_RESULTS,
            pageToken=next_page_token or ""
        ).execute()

        for item in resp['items']:
            r = item['snippet']
            replies.append({
                'thread_id': None,
                'comment_id': item['id'],
                'author': r['authorDisplayName'],
                'published_at': r['publishedAt'],
                'like_count': r['likeCount'],
                'text': r['textOriginal'],
                'is_reply': True,
                'parent_id': parent_id
            })

        next_page_token = resp.get('nextPageToken')
        if not next_page_token:
            break

    return replies

# --- Main script ---

all_comments = []

In [23]:
# 1) Fetch every top-level thread
threads = fetch_all_threads(vidid)

In [24]:
# 2) For each thread, fetch its replies
for t in threads:
    all_comments.append([
        t['author'], t['published_at'], t['like_count'], t['text'], t['is_reply'], t['id'], t['parent_id']
    ])
    replies = fetch_all_replies(t['comment_id'])
    for r in replies:
        all_comments.append([
            r['author'], r['published_at'], r['like_count'], r['text'], r['is_reply'], r['id'], r['parent_id']
        ])

In [28]:
# 3) Dump to DataFrame
df = pd.DataFrame(
    all_comments,
    columns=['author', 'updated_at', 'like_count', 'text', 'is_reply', 'id', 'parent_id']
)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7589 entries, 0 to 7588
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   author      7589 non-null   object
 1   updated_at  7589 non-null   object
 2   like_count  7589 non-null   int64
 3   text        7589 non-null   object
 4   is_reply    7589 non-null   bool
 5   parent_id   2635 non-null   object
dtypes: bool(1), int64(1), object(4)
memory usage: 304.0+ KB

In [29]:
df.head(50)

,author,updated_at,like_count,text,is_reply,parent_id
0,@TheDiaryOfACEO,2025-05-12T07:01:17Z,968,question? do you like these types of convos? I...,False,None
1,@meermohammad3678,2025-05-12T07:07:53Z,18,Bring Dr Andy Galpin once again Steven.,True,UgzgnvJK2ZQDimebgQ94AaABAg
2,@baby_bear01,2025-05-12T07:08:11Z,11,I would love to see more like this!,True,UgzgnvJK2ZQDimebgQ94AaABAg
3,@Abraxxas-p2t,2025-05-12T07:11:31Z,25,Such conversations are interesting but your in...,True,UgzgnvJK2ZQDimebgQ94AaABAg
4,@85yugs,2025-05-12T07:13:25Z,1,"The ones who want AI are the same cowards, cou...",True,UgzgnvJK2ZQDimebgQ94AaABAg
5,@breakthruuu,2025-05-12T07:17:07Z,2,A$I 📈💥♾️,True,UgzgnvJK2ZQDimebgQ94AaABAg
6,@soldbyauthor,2025-05-12T07:18:59Z,7,"Steven, please, read my comment!! I have email...",True,UgzgnvJK2ZQDimebgQ94AaABAg
7,@jasleelosmith,2025-05-12T07:36:15Z,5,MORE PANDEL DISCUSSION PLEASE!!! And bring thi...,True,UgzgnvJK2ZQDimebgQ94AaABAg
8,@theoldlady2804,2025-05-12T07:56:11Z,7,"Yes, would live to see the opposing viewpoints...",True,UgzgnvJK2ZQDimebgQ94AaABAg
9,@robinspat,2025-05-12T08:08:04Z,2,But not use of word convo 👀,True,UgzgnvJK2ZQDimebgQ94AaABAg
10,@FrancisPindar,2025-05-12T08:28:36Z,6,Having thought leaders like you and Daniel dis...,True,UgzgnvJK2ZQDimebgQ94AaABAg
11,@lydiacliff,2025-05-12T08:28:40Z,1,Get Bill Gates on the pod!!,True,UgzgnvJK2ZQDimebgQ94AaABAg
12,@fireandforte,2025-05-12T08:44:45Z,7,Yes! Fantastic varied debate. So far I think o...,True,UgzgnvJK2ZQDimebgQ94AaABAg
13,@dplj4428,2025-05-12T08:50:17Z,2,41:25 Software bugs have sometimes become feat...,True,UgzgnvJK2ZQDimebgQ94AaABAg
14,@MaudMargretheRex,2025-05-12T09:05:04Z,7,"This wasn’t about ai 🤖, it was merely about ho...",True,UgzgnvJK2ZQDimebgQ94AaABAg
15,@keepcreationprocess,2025-05-12T09:18:12Z,1,I don't know yet. I am still thinking,True,UgzgnvJK2ZQDimebgQ94AaABAg
16,@Truthseeker-cx46g,2025-05-12T09:31:52Z,0,Why does a teacher at the blackboard still hav...,True,UgzgnvJK2ZQDimebgQ94AaABAg
17,@Truthseeker-cx46g,2025-05-12T09:38:45Z,0,Only very few people today fully realize how r...,True,UgzgnvJK2ZQDimebgQ94AaABAg
18,@Doe-Nutz72,2025-05-12T09:38:56Z,7,Your Panel Lacks Expertise on the Subject.\nPh...,True,UgzgnvJK2ZQDimebgQ94AaABAg
19,@soldbyauthor,2025-05-12T09:46:02Z,3,"@aimcgarry if they do that, it ends their topi...",True,UgzgnvJK2ZQDimebgQ94AaABAg
20,@Truthseeker-cx46g,2025-05-12T09:48:40Z,1,Which boss of office or company will pay someb...,True,UgzgnvJK2ZQDimebgQ94AaABAg
21,@futures2247,2025-05-12T10:36:28Z,0,seems to me the biggest risk of AI isn't AI bu...,True,UgzgnvJK2ZQDimebgQ94AaABAg
22,@NerminLipovac,2025-05-12T10:41:12Z,1,"I like listening to your content, and what I a...",True,UgzgnvJK2ZQDimebgQ94AaABAg
23,@bzxcv98760,2025-05-12T10:50:13Z,1,subbed - i been shouting these conversations n...,True,UgzgnvJK2ZQDimebgQ94AaABAg
24,@bzxcv98760,2025-05-12T10:50:43Z,1,@@soldbyauthor what is your book?,True,UgzgnvJK2ZQDimebgQ94AaABAg
25,@shamgar_6009,2025-05-12T10:54:19Z,10,I like the convo just not the panel presented....,True,UgzgnvJK2ZQDimebgQ94AaABAg
26,@guiltazaour2871,2025-05-12T11:20:46Z,0,"yes, this is more interesting than a 1 to 1 co...",True,UgzgnvJK2ZQDimebgQ94AaABAg
27,@NJTremblay-dp4gr,2025-05-12T11:21:09Z,1,these type of conversations are needed more th...,True,UgzgnvJK2ZQDimebgQ94AaABAg
28,@TheJzbond,2025-05-12T11:43:43Z,1,I have a business idea (if you’re willing to s...,True,UgzgnvJK2ZQDimebgQ94AaABAg
29,@JoJo-l9g1u,2025-05-12T11:43:54Z,4,The conversation is good but the dark set is b...,True,UgzgnvJK2ZQDimebgQ94AaABAg
30,@cathleenmcmahan8794,2025-05-12T11:47:29Z,1,Space weather news guy looking for a good plat...,True,UgzgnvJK2ZQDimebgQ94AaABAg
31,@brotherbarnes,2025-05-12T12:10:51Z,1,Would have been great if it had actually been ...,True,UgzgnvJK2ZQDimebgQ94AaABAg
32,@shermwormsall,2025-05-12T12:18:06Z,1,You are missing the AI pros who are building c...,True,UgzgnvJK2ZQDimebgQ94AaABAg
33,@LewisDecodesAI,2025-05-12T12:19:41Z,0,02:20:20 shows how much humanity is disconnect...,True,UgzgnvJK2ZQDimebgQ94AaABAg
34,@chuyhable,2025-05-12T12:41:04Z,0,Love it. Im missing a more academic perspectiv...,True,UgzgnvJK2ZQDimebgQ94AaABAg
35,@cecilia9364,2025-05-12T12:42:55Z,0,Absolutely! Thank you,True,UgzgnvJK2ZQDimebgQ94AaABAg
36,@alfredlear4141,2025-05-12T12:43:37Z,0,"Very good, currently at work listening for the...",True,UgzgnvJK2ZQDimebgQ94AaABAg
37,@thecultofgolf2810,2025-05-12T12:45:19Z,1,I have followed and watched everything you rel...,True,UgzgnvJK2ZQDimebgQ94AaABAg
38,@clintondavispersonal,2025-05-12T12:54:25Z,0,"Yes, well balanced and very interesting, thank...",True,UgzgnvJK2ZQDimebgQ94AaABAg
39,@saronmoges7463,2025-05-12T13:03:13Z,0,Look check about the ai racist also ai ethics ...,True,UgzgnvJK2ZQDimebgQ94AaABAg
40,@mraarone,2025-05-12T13:05:02Z,0,"Yeah, it’s cool, especially when you have a sc...",True,UgzgnvJK2ZQDimebgQ94AaABAg
41,@ItsMe-ic7on,2025-05-12T13:24:31Z,1,AI is not going to be a benefit AI is going to...,True,UgzgnvJK2ZQDimebgQ94AaABAg
42,@jayviolentmob8309,2025-05-12T13:26:03Z,4,"I find these conversations, and especially the...",True,UgzgnvJK2ZQDimebgQ94AaABAg
43,@jillhumphreys5808,2025-05-12T13:39:46Z,3,So most of these comments ask for more clarity...,True,UgzgnvJK2ZQDimebgQ94AaABAg
44,@DontBeALlama,2025-05-12T13:51:10Z,0,We need to be worried about the US and Israel ...,True,UgzgnvJK2ZQDimebgQ94AaABAg
45,@kunjanghimire5898,2025-05-12T13:53:11Z,0,What AI agents they are talking about that sta...,True,UgzgnvJK2ZQDimebgQ94AaABAg
46,@Growmap,2025-05-12T14:02:21Z,1,Humans have consistently failed to foresee the...,True,UgzgnvJK2ZQDimebgQ94AaABAg
47,@Geffect-Foundr,2025-05-12T14:05:02Z,3,The world should put a stop to this corporate ...,True,UgzgnvJK2ZQDimebgQ94AaABAg
48,@ThatsnotwhereIparkedmycar,2025-05-12T14:07:37Z,0,"Great convo, Steven! Love how your guests resp...",True,UgzgnvJK2ZQDimebgQ94AaABAg
49,@rodneyericjohnson,2025-05-12T14:12:47Z,0,"Inviting that racist charlatan, Bret Weinstein...",True,UgzgnvJK2ZQDimebgQ94AaABAg

## Sort by Likes and Get Top 10

In [6]:
df.sort_values(by='like_count', ascending=False)[0:10]

,author,updated_at,like_count,text,public
778,@dirtsmegee,2023-10-23T15:05:54Z,1120,Action needs an 8 part series in every country...,True
0,@TheDiaryOfACEO,2025-05-12T07:01:17Z,960,question? do you like these types of convos? I...,True
681,@Nolanbrown480,2023-10-23T16:59:12Z,777,Clovis’ energy is absolutely unmatched. The pe...,True
646,@ActionBronsonMusic,2023-10-23T17:53:02Z,608,PARIS. WITH LOVE.,True
783,@uknownutin3528,2023-10-23T15:01:03Z,552,One of the best food series on YouTube. LONG L...,True
792,@PinoPP,2023-10-23T12:30:09Z,282,One of the best and most authentic eating shows,True
732,@urbanprojectz,2023-10-23T15:59:02Z,180,This is a game changer for food/cooking/review...,True
662,@yorkshireguy6671,2023-10-23T17:15:43Z,78,Action and Clovis in Paris always looks like t...,True
756,@elmejortrabajodelmundo,2023-10-23T15:26:47Z,76,"""From Paris with Love"" makes me happy for real...",True
791,@cheng8841,2023-10-23T12:57:26Z,70,"""eight part series"" LETS GOOOOOO",True

#Pull all Comments for Multiple Videos

## 1. Get Comments Function

In [12]:
import googleapiclient.discovery
import pandas as pd

api_service_name = "youtube"
api_version = "v3"
DEVELOPER_KEY = dev

youtube = googleapiclient.discovery.build(
    api_service_name, api_version, developerKey=DEVELOPER_KEY)


def getcomments(video):
  request = youtube.commentThreads().list(
      part="snippet",
      videoId=video,
      maxResults=100
  )

  comments = []

  # Execute the request.
  response = request.execute()

  # Get the comments from the response.
  for item in response['items']:
      comment = item['snippet']['topLevelComment']['snippet']
      public = item['snippet']['isPublic']
      comments.append([
          comment['authorDisplayName'],
          comment['publishedAt'],
          comment['likeCount'],
          comment['textOriginal'],
          comment['videoId'],
          public
      ])

  while (1 == 1):
    try:
     nextPageToken = response['nextPageToken']
    except KeyError:
     break
    nextPageToken = response['nextPageToken']
    # Create a new request object with the next page token.
    nextRequest = youtube.commentThreads().list(part="snippet", videoId=video, maxResults=100, pageToken=nextPageToken)
    # Execute the next request.
    response = nextRequest.execute()
    # Get the comments from the next response.
    for item in response['items']:
      comment = item['snippet']['topLevelComment']['snippet']
      public = item['snippet']['isPublic']
      comments.append([
          comment['authorDisplayName'],
          comment['publishedAt'],
          comment['likeCount'],
          comment['textOriginal'],
          comment['videoId'],
          public
      ])

  df2 = pd.DataFrame(comments, columns=['author', 'updated_at', 'like_count', 'text','video_id','public'])
  return df2

In [13]:
df = getcomments('JMYQmGfTltY')
df

,author,updated_at,like_count,text,video_id,public
0,@TheDiaryOfACEO,2025-05-12T07:01:17Z,964,question? do you like these types of convos? I...,JMYQmGfTltY,True
1,@s1dubbzz751,2025-05-14T14:18:53Z,0,AI automation along with fiat currency which a...,JMYQmGfTltY,True
2,@thefutureisnow462,2025-05-14T14:18:37Z,0,"""I want to cede control to an entity that will...",JMYQmGfTltY,True
3,@lucyannhuxter,2025-05-14T14:18:18Z,0,"1:48 Brett, “Can we bring everybody along?”\nE...",JMYQmGfTltY,True
4,@HiDefBarskie,2025-05-14T14:18:11Z,0,Kinda sounds like a HUGE CASH grab before the ...,JMYQmGfTltY,True
...,...,...,...,...,...,...
4940,@m10h9T5SiSi,2025-05-12T07:01:03Z,1,Thank you very much for your fascinating video...,JMYQmGfTltY,True
4941,@m10h9T5Ruongng,2025-05-12T07:01:00Z,2,Keep sharing your talents. Your videos are enj...,JMYQmGfTltY,True
4942,@user_drwuf0,2025-05-12T07:01:00Z,1,Keep sharing your art. Your videos bring joy a...,JMYQmGfTltY,True
4943,@user_735j67,2025-05-12T07:00:58Z,1,Continue to delight us with your videos! Your ...,JMYQmGfTltY,True
4944,@user_ij1p7y,2025-05-12T07:00:53Z,1,Keep giving us your highlights! Your videos ad...,JMYQmGfTltY,True

## 2. For Loop for List of IDs

In [15]:
df = pd.DataFrame()
for i in ['JMYQmGfTltY']:
  df2 = getcomments(i)
  df = pd.concat([df, df2])

In [16]:
df

,author,updated_at,like_count,text,video_id,public
0,@TheDiaryOfACEO,2025-05-12T07:01:17Z,964,question? do you like these types of convos? I...,JMYQmGfTltY,True
1,@s1dubbzz751,2025-05-14T14:18:53Z,0,AI automation along with fiat currency which a...,JMYQmGfTltY,True
2,@thefutureisnow462,2025-05-14T14:18:37Z,0,"""I want to cede control to an entity that will...",JMYQmGfTltY,True
3,@lucyannhuxter,2025-05-14T14:18:18Z,0,"1:48 Brett, “Can we bring everybody along?”\nE...",JMYQmGfTltY,True
4,@HiDefBarskie,2025-05-14T14:18:11Z,0,Kinda sounds like a HUGE CASH grab before the ...,JMYQmGfTltY,True
...,...,...,...,...,...,...
4940,@m10h9T5SiSi,2025-05-12T07:01:03Z,1,Thank you very much for your fascinating video...,JMYQmGfTltY,True
4941,@m10h9T5Ruongng,2025-05-12T07:01:00Z,2,Keep sharing your talents. Your videos are enj...,JMYQmGfTltY,True
4942,@user_drwuf0,2025-05-12T07:01:00Z,1,Keep sharing your art. Your videos bring joy a...,JMYQmGfTltY,True
4943,@user_735j67,2025-05-12T07:00:58Z,1,Continue to delight us with your videos! Your ...,JMYQmGfTltY,True
4944,@user_ij1p7y,2025-05-12T07:00:53Z,1,Keep giving us your highlights! Your videos ad...,JMYQmGfTltY,True

In [17]:
df['video_id'].value_counts()

video_id
JMYQmGfTltY    4945
Name: count, dtype: int64